# ruff: noqa: F401
from __future__ import annotations

from .diff import (
    GIT_DIFF_SENTINEL,
    _fallback_gitignore_matches,
    _git_diff,
    _git_head,
    _gitignore_pattern_matches,
    _gitignored_paths,
    _inline_diff_source,
    _load_diff,
    _normalize_diff_path,
    _parse_changed_files,
    _parse_git_check_ignore_output,
    _root_gitignore_patterns,
)
from .eval import (
    RETRIEVAL_EVAL_VERSION,
    RETRIEVAL_FIXTURE_VERSION,
    _load_fixture,
    _ratio,
    _resolve_fixture_path,
    _retrieved_paths_for_fixture_task,
    _string_set,
    evaluate_retrieval,
)
from .impact import (
    IMPACT_CONTRACT_VERSION,
    LEXICAL_SYMBOL_MAX_DOCUMENT_FRACTION,
    LEXICAL_SYMBOL_MIN_DOCUMENT_LIMIT,
    LIKELY_IMPACTED_LIMIT,
    TARGETED_TEST_SUGGESTION_LIMIT,
    _changed_file_entries,
    _document_frequency,
    _lexical_symbol_document_limit,
    _likely_impacted_entries,
    _omitted_changed_entries,
    _safe_snapshot_files,
    _safe_snapshot_files_by_path,
    _symbol_is_too_common,
    _verification_suggestions,
    analyze_impact,
)
from .receipts import (
    CONTEXT_RECEIPT_VERSION,
    _included_candidate_context,
    _receipt_payload,
    _record_context_receipt,
)
from .scan import (
    DEFAULT_CODE_INDEX_EXCLUDES,
    DEFAULT_IGNORED_NAMES,
    DEFAULT_SENSITIVE_EXCLUDES,
    INDEX_VERSION,
    LANGUAGE_BY_SUFFIX,
    LARGE_FILE_BYTES,
    IgnoredEntry,
    IndexedFile,
    ScanResult,
    SensitiveIndexSettings,
    _code_index_exclude_patterns,
    _configured_ignore_reason,
    _configured_yaml_list,
    _default_ignore_reason,
    _detect_language,
    _line_count,
    _looks_binary,
    _matches_any_pattern,
    _parse_inline_yaml_list,
    _path_pattern_matches,
    _relative_path,
    _scan_working_tree,
    _sensitive_ignore_reason,
    _sensitive_index_settings,
    _sensitive_override_warning,
    _sha256_file,
    _strip_yaml_string,
    _symbol_summary,
    _unique_nonempty,
)
from .search import (
    CODE_SEARCH_VERSION,
    SEARCH_SNIPPET_CHARS,
    _is_definition_like_line,
    _line_search_score,
    _search_normalized,
    _search_payload,
    _search_result_lines,
    _search_score,
    _snippet,
    search_code,
)
from .store import (
    ID_NUMBER_RE,
    IndexSnapshot,
    _build_index_payload,
    _counted_path_warning,
    _ensure_index_schema,
    _index_summary,
    _json_object,
    _latest_snapshot,
    _load_required_snapshot,
    _next_numeric_suffix,
    _staleness_warnings_for_snapshot,
    _summary_sensitive_omitted_count,
    build_code_index,
    code_index_status,
)
from .symbols import (
    JS_CLASS_RE,
    JS_EXPORT_BINDING_RE,
    JS_EXPORT_LIST_RE,
    JS_FUNCTION_RE,
    MD_HEADING_RE,
    PYTHON_CLASS_RE,
    PYTHON_DEF_RE,
    SYMBOL_SUMMARY_VERSION,
    _empty_symbol_summary,
    _file_mentions,
    _javascript_symbols,
    _markdown_symbols,
    _python_symbols,
    _symbol_names,
)
from .test_hints import (
    TEST_HINT_VERSION,
    _attach_test_hints,
    _empty_test_hint,
    _identifier_tokens,
    _is_test_path,
    _python_imported_modules,
    _python_module_name,
    _python_test_import_reasons,
    _stem_key,
    _test_hint_for_file,
    _test_path_matches_changed_path,
    _test_path_matches_source_surface,
)

__all__ = [name for name in globals() if not name.startswith("__")]
