"""Stable, versioned artifact contracts exposed by Project Loop Harness."""

from .completion_packet import (
    COMPLETION_PACKET_CONTRACT_VERSION,
    CompletionPacketValidationResult,
    calculate_proof_level,
    canonical_json,
    completion_packet_schema,
    compute_packet_id,
    load_completion_packet,
    validate_completion_packet,
    with_computed_packet_id,
)
from .handoff_packet import (
    HANDOFF_PACKET_CONTRACT_VERSION,
    HandoffPacketValidationResult,
    compute_packet_id as compute_handoff_packet_id,
    finalize_handoff_packet,
    handoff_packet_schema,
    load_handoff_packet,
    validate_handoff_packet,
)
from .work_brief import (
    WORK_BRIEF_CONTRACT_VERSION,
    WorkBriefValidationResult,
    canonical_work_brief_json,
    load_work_brief,
    serialized_work_brief,
    validate_work_brief,
    work_brief_schema,
    work_brief_sha256,
)
from .route_recommendation import (
    ROUTE_POLICY_VERSION,
    ROUTE_RECOMMENDATION_CONTRACT_VERSION,
    RouteRecommendationValidationResult,
    canonical_route_recommendation_json,
    load_route_recommendation,
    route_recommendation_schema,
    serialized_route_recommendation,
    validate_route_recommendation,
)
from .route_override import (
    ROUTE_OVERRIDE_CONTRACT_VERSION,
    RouteOverrideValidationResult,
    canonical_route_override_json,
    load_route_override,
    route_override_schema,
    serialized_route_override,
    validate_route_override,
)
from .evidence_set import (
    EVIDENCE_SET_CONTRACT_VERSION,
    REPORT_MANIFEST_CONTRACT_VERSION,
    EvidenceSetValidationResult,
    canonical_evidence_set_json,
    evidence_set_schema,
    load_evidence_set,
    serialized_evidence_set,
    validate_evidence_set,
)
from .completion_policy import (
    COMPLETION_EVALUATION_CONTRACT_VERSION,
    COMPLETION_POLICY_CONTRACT_VERSION,
    CompletionPolicyValidationResult,
    canonical_completion_policy_json,
    completion_policy_schema,
    load_completion_policy,
    validate_completion_policy,
)

__all__ = [
    "COMPLETION_PACKET_CONTRACT_VERSION",
    "CompletionPacketValidationResult",
    "calculate_proof_level",
    "canonical_json",
    "completion_packet_schema",
    "compute_packet_id",
    "load_completion_packet",
    "validate_completion_packet",
    "with_computed_packet_id",
    "HANDOFF_PACKET_CONTRACT_VERSION",
    "HandoffPacketValidationResult",
    "compute_handoff_packet_id",
    "finalize_handoff_packet",
    "handoff_packet_schema",
    "load_handoff_packet",
    "validate_handoff_packet",
    "WORK_BRIEF_CONTRACT_VERSION",
    "WorkBriefValidationResult",
    "canonical_work_brief_json",
    "load_work_brief",
    "serialized_work_brief",
    "validate_work_brief",
    "work_brief_schema",
    "work_brief_sha256",
    "ROUTE_POLICY_VERSION",
    "ROUTE_RECOMMENDATION_CONTRACT_VERSION",
    "RouteRecommendationValidationResult",
    "canonical_route_recommendation_json",
    "load_route_recommendation",
    "route_recommendation_schema",
    "serialized_route_recommendation",
    "validate_route_recommendation",
    "ROUTE_OVERRIDE_CONTRACT_VERSION",
    "RouteOverrideValidationResult",
    "canonical_route_override_json",
    "load_route_override",
    "route_override_schema",
    "serialized_route_override",
    "validate_route_override",
    "EVIDENCE_SET_CONTRACT_VERSION",
    "REPORT_MANIFEST_CONTRACT_VERSION",
    "EvidenceSetValidationResult",
    "canonical_evidence_set_json",
    "evidence_set_schema",
    "load_evidence_set",
    "serialized_evidence_set",
    "validate_evidence_set",
    "COMPLETION_EVALUATION_CONTRACT_VERSION",
    "COMPLETION_POLICY_CONTRACT_VERSION",
    "CompletionPolicyValidationResult",
    "canonical_completion_policy_json",
    "completion_policy_schema",
    "load_completion_policy",
    "validate_completion_policy",
]
